services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acto
      MYSQL_USER: acto
      MYSQL_PASSWORD: acto
    ports:
      - "33061:3306"
  redis:
    image: redis:7
    ports:
      - "63791:6379"
